# -*- coding: utf-8 -*-
"""New-User.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H9Pzk5UczJsRcfXr5sm1T96T16LBCeDi
"""

import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt
import seaborn as sns
import operator

"""new user => generate id (append user table)  -->
user_last_used_id+1

=> trending (popularity based)

  => rating table => avg rating => sort 
  
  => top 5 paper of each field
"""



df=pd.read_csv("Rating.csv")
df

field_dict = {0:'Artificial Intelligence',1:'Machine Learning', 2:'Software Engineering',3:'Math',4:'Physics',5:'Quantum Computing',6:'Data Structures',7:'Cryptography and Security',8:'Computer Vision',9:'others'}

# see later- 0- not read

arr=df.sum(axis=1)
arr=arr/df.shape[1]
arr

enumerate_object = enumerate(arr)
sorted_pairs = sorted(enumerate_object, key=operator.itemgetter(1))

sorted_indices = []
for index, element in sorted_pairs:
    sorted_indices.append(index)
sorted_indices.reverse()
print(sorted_indices)

dataf = pd.read_csv("rp_final.csv")

# top 5 papers in  each field
for i in sorted_indices:
  field_name = field_dict[i]
  blah = dataf[dataf['Field']==field_name].sort_values(by='Citations',ascending = False)
  l=blah.index.values
  # print(blah)
  print(l)

df['user_'+str(df.shape[1])] = [0 for i in range((df.shape[0]))]

df

